language: node_js
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm run migrations
after_script:
- npm run coverage
services:
- postgresql
node_js:
- node
- '6'
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=test
  - URL_TEST=postgres://postgres@localhost/travis_ci_test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
- npm run transpile
deploy:
  provider: heroku
  api_key:
    secure: "Kqb5CqjvVkz+GrMBI/woUJLg7CBBhgp6m6qTEEPA0kLCHnFwp3CBwDYA/lozhvWkmjUVjBu0K590F/MEaMcnFWGOt3GKrczsmINh8+7Ro/gbzUuTAEABv+DPIsW6kg
TJ48IWTxvbulHFglBFObsLiHLNEx3QIWuYpBuCIYoCQzXaIkLO8uL2s9j8YKOVt8kLRok0F1S4Tlh8PJBORmHy9YHE0+jDup1RuOK9aQanzJMb6tNZI2pYZJpmCGIcZEv0RDus7YY
kHb0xzka8mq9FsZl9pDKaN5rlvYF5tTk7sosd/41OOGlZpGzO6YlUvQpiJ153S+AlpT4B2ixn0d2z5A19nhBOzPK9T/8RhQeS53ryGiBx5dz4F8tTHQkkZxRijzc7BddIJRdSSVmK
mdkCwjHYQPhttRKNTQqW5Acns3JiD2qeXqYSjUs9QO/JjmgetRme7gd+XpUixWuPzAOIWUFPil24dA2v/m7C186JXYxOQwWeaMHh51coCDhR5B3xpQBNIZyW47KJCo+1VG2e15Y8K
UAX9oOFwqIMw/HkVD8WbVm7VeNsovF0HYQtcasTPU/appi6FhOr7DjscrLXQt76f/H6DpuPuNWFgX4mD3y2LQn8AEMWt4OIzRYPpmENvoZBo2DdPygK3Xdm9EwbMYEYcbKG/e/pxb
u7NbbEN5Q="
  app: app-postit
  on: develop
  run:
  - npm install
  - npm run migrations
  - npm start