language: node_js
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run migrations
services:
  - postgresql
node_js:
  - "node"
  - "6"
env:
  - CXX=g++-4.8
  - NODE_ENV=test
  - URL_TEST=postgres://postgres@localhost/travis_ci_test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8