language: node_js
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm run migrations
after_script:
- npm run coverage
services:
- postgresql
node_js:
- node
- '6'
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=test
  - URL_TEST=postgres://postgres@localhost/travis_ci_test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
- npm run transpile
deploy:
  provider: heroku
  api_key:
    secure: hSM+gUAeUvfWsqhCg/1MJQfD+u0aj1/zSONvZ9/fhTgMbKLK8Y8izBB1eNajkCetRqpATzj7bPpv3uSKaqIiOXmPcE91HCcYT5OZnC9TJOOtfp99J5BaQhOlBfV9YjEfb/ENtYuCkDMwbz5wsyXlYyLZwYZIJpxEa9g6FFN36/KTl/qq3o2Ut3+Awjuk2eqLCBXMoPfrLrAHAyjj9O9cWFtCP5XDiE340y5eULMwTHlJrD/jXeYVZcNQmmBrUkgtAPN63d+At8GMjc2cQXBv4D8M+rQLSN/fQBsGmRX4ijdkrBxblLWmlj2lF4bs4MMsT/+2md/32+KzkH2ay6swLyawr6KyfINkalrvxCfO9CleELeJMhH2bcB9J8/viIQELS8mvhOGGCywiKH1p29mFtipgnetq0Eu8188cDF6NNGNqO14rmzmuiUqEiwLdyMqDU2HWQLs4JTLScDL1pBtj4A/GWrHmpasLG2mL2cbAQkusMkjVRM/cxnD6575V5A2JQKGwHFQo5UJSOuq3UXBZGG6EJxvqRcD8B9+TBqu0LxYEgepB5MdRSRi+yvHtFjtkOPBGXxS2BB03Msaq/c8nsYtNziPICoqa3pLs+Rzu4KFXZVXdC3fGP3fyd35Fb9CDuitfmg1xHq+8jwePNTLkjhFIVFSwc1vvnWHs97Us7c=
  app: app-postit
  on: develop
  run:
  - npm install
  - npm run migrations
  - npm start
