language: node_js
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm run migrations
after_script:
- npm run coverage
services:
- postgresql
node_js:
- node
- '6'
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=test
  - URL_TEST=postgres://postgres@localhost/travis_ci_test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
- npm run transpile
deploy:
  provider: heroku
  api_key:
    secure: st76KouV7qjyHziRxl3K8rUA1qvOe2cEpTjivd7haXqNEasDIYlbYpF6VW0Cln1ChtQXYrEDTsO1sPm6R2oZ4Xxz4iJMxKYvpTp6w9vae9OTQgpVRj8+/rX8E/oNpfTY38A3GF/T9bJKi5bpml2LdtI3jOXVHtaRsE65ZwS0CO3idB0EhdmjJQk5ofz+y7vToin7YVZwIm/xwRBFI1Ki2OYvnJoo8pBeIuvWbtUb1SqzTIFr0BiiXlhKLVPkEK8/kOnV3YeTOH7OCeciLZDFmWl12FT7/nJVUan6q2E7amCGZRABxVCqjn7ECzHM3YyM4drMX5+WEknV9OfpVcgFTkeMi3WQeFTO1QkNygG5xrX4wokc53r/pp3UhtSYd15P82o4gKGPrmVKM3QgL1bzbHAU+E6DwH3FplGCR6a3E5Li8RgA2eYdvQkmN6kGEN2Cy0J8inkxZ14YswGOjiTA5ksuMzL9FdBN6PY6CiRPRgUcBVwa4XyeGBWNuvTVZDOcGUQTXqxTuuhUIvvQB5b9LztWeT9K+nKrh6WpT/LB8Fp4HFZSrQCZSqKp7/gGqBBfLWATjm9HREsc8KT43ySu0Z9vp1iqfMEEVJp0ijZD+VRMuFtIpA3FlWGe541tJYdsrNDh1cIhnerF7/9X5ahWjLFwWImfi9HdIDDqvvahC7U=
  app: app-postit
  on: develop
  run:
  - npm install
  - npm run migrations
  - npm start
